name: ${project.name}
version: ${project.version}
main: com.wunanc.DomFly.DomFly
api-version: '1.21'
authors: [Hotguo,MingLi]
description: Dom领地飞行插件
folia-supported: true
website: https://github.com/wunanc/DomFly

commands:
  domfly:
    description: DomFly的权限控制
    usage: /domfly [help|reload|undomfly <player>]
    permission: domfly.use
    permission-message: "§c你没有权限使用此命令!"

permissions:
  domfly.use:
    description: "允许使用领地飞行"
    default: op
  domfly.admin:
    description: "管理员权限"
    default: op
    children:
      domfly.use: true
